### PR TITLE
Feature/bitemporal

### PR DESCRIPTION
**Pull request by ealonsodb**
Andres, please review this to mergue, it executes all unit Tests ok

### CODE REVIEW

**Comment by stratiocommit** [comment]
Jenkins job pending... wait for confirmation message before merging.

**Comment by stratiocommit** [comment]
Jenkins job went OK. Its up to someone to merge.

**Comment by stratiocommit** [comment]
Jenkins job pending... wait for confirmation message before merging.

**Comment by stratiocommit** [comment]
Jenkins job went OK. Its up to someone to merge.

**Comment by adelapena** [comment]
Done. Thanks!

**Pull request merged**
